//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FlashReader.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_BASE_RECORDS                103
#define IDD_PAGE_SELECT                 107
#define IDR_MAINFRAME                   128
#define IDR_FlashReaderTYPE             129
#define IDD_SELECT_READER               130
#define IDB_DEVICES                     131
#define IDD_RECORD_EDIT                 133
#define IDD_BASE_EDIT                   134
#define IDD_FLASHREADER_FORM            135
#define IDD_FLASH_PARAMETERS            136
#define IDD_VENDOR_RECORDS              137
#define IDD_VENDOR_NEW                  138
#define IDD_FLASH_INFO                  139
#define IDB_STATES                      141
#define IDB_PAGE_STATE                  142
#define IDD_SETTINGS                    146
#define IDD_CHANGE_PAGE_STATE           147
#define IDR_MENU_NEW_STATE              148
#define IDD_PAGE_START                  151
#define IDD_PAGE_FINISH                 152
#define IDD_NEW_TASK                    154
#define IDD_UPDATE_RECORD               155
#define IDR_MENU_BMP                    156
#define IDC_APP_NAME                    1000
#define IDC_APP_VERSION                 1001
#define IDC_APP_COPYRIGHT               1002
#define IDC_TREE_DEVICES                1003
#define IDC_COMBO_CMD_CYCLE             1004
#define IDC_COMBO_FULL_ADR_CYCLE        1005
#define IDC_COMBO_PAGE_ADR_CYCLE        1006
#define IDC_COMBO_SPEED                 1007
#define IDC_COMBO_POWER_IO              1008
#define IDC_COMBO_ONFI                  1009
#define IDC_COMBO_BUS                   1010
#define IDC_EDIT_PARTNUMBER             1011
#define IDC_EDIT_PAGE_SIZE              1012
#define IDC_EDIT_PAGE_BLOCK             1013
#define IDC_EDIT_BLOCK_LU               1014
#define IDC_GEOMETRY                    1015
#define IDC_COMBO_CMD_TYPE              1017
#define IDC_EDIT_LU_CS                  1019
#define IDC_COMBO_VENDOR                1020
#define IDC_COMBO_CS_CHIP               1021
#define IDC_LIST_RECORDS                1023
#define IDC_FILTER_CS                   1024
#define IDC_FILTER_PAGE_SIZE            1025
#define IDC_FILTER_TOTAL_SIZE           1026
#define IDC_BTN_NEW                     1027
#define IDC_BTN_EDIT                    1028
#define IDC_INFO_SIZE                   1029
#define IDC_BTN_REMOVE                  1030
#define IDC_INFO_BUS                    1031
#define IDC_INFO_COMMAND                1032
#define IDC_BTN_VENDORS                 1033
#define IDC_INFO_SPEED                  1034
#define IDC_INFO_VCC_IO                 1035
#define IDC_FILTER_VENDOR               1036
#define IDC_INFO_ONFI                   1037
#define IDC_FILTER_BUS                  1038
#define IDC_INFO_GEOMETRY               1039
#define IDC_INFO_PARTNUMBER             1040
#define IDC_LIST_VENDORS                1041
#define IDC_BTN_VENDOR_NEW              1042
#define IDC_BTN_VENDOR_REMOVE           1043
#define IDC_EDIT_VENDOR_ID              1044
#define IDC_EDIT_VENDOR_NAME            1045
#define IDC_BASE_RECORDS                1046
#define IDC_FLASH_PARAMETERS            1047
#define IDC_FLASH_INFO                  1048
#define IDC_CURRENT_FLASH               1051
#define IDC_RE_LOG                      1052
#define IDC_RADIO_ONCE                  1053
#define IDC_RADIO_VERIFY                1054
#define IDC_RADIO_REPAIR                1055
#define IDC_PROGRESS_STEP               1057
#define IDC_FRAME_LOG                   1058
#define IDC_STATE_NO                    1060
#define IDC_STATE_ONCE                  1061
#define IDC_STATE_VER_ERR               1062
#define IDC_STATE_VER_OK                1063
#define IDC_STATE_COR_HI                1064
#define IDC_STATE_COR_LOW               1065
#define IDC_SLIDER_LIMIT                1066
#define IDC_ID_AND_VENDOR               1067
#define IDC_LIMIT_VALUE                 1068
#define IDC_SLIDER_DELTA                1069
#define IDC_DELTA_VALUE                 1070
#define IDC_BTN_DEFAULTS                1071
#define IDC_STEP_COUNT                  1072
#define IDC_COMBO_NEW_STATE             1073
#define IDC_RADIO_GLOBAL                1077
#define IDC_RADIO_GEOMETRY              1078
#define IDC_RADIO_ALL                   1079
#define IDC_RADIO_CS                    1080
#define IDC_RADIO_BLOCK                 1081
#define IDC_RADIO_PAGE                  1082
#define IDC_EDIT_FROM_PAGE              1083
#define IDC_EDIT_TO_PAGE                1084
#define IDC_EDIT_FROM_BLOCK             1085
#define IDC_EDIT_TO_BLOCK               1086
#define IDC_EDIT_FROM_CS                1087
#define IDC_EDIT_TO_CS                  1089
#define IDC_GROUP_INFO                  1090
#define IDC_LABLE_CHECK                 1091
#define IDC_LABLE_ONCE                  1092
#define IDC_LABLE_VERIFY                1093
#define IDC_LABLE_CORRECTION            1094
#define IDC_LABLE_CS0                   1095
#define IDC_LABLE_CS1                   1096
#define IDC_LABLE_CS2                   1097
#define IDC_LABLE_CS3                   1098
#define IDC_FLASH_TOTAL_SIZE            1099
#define IDC_CHECK_LOG_ENABLE            1100
#define IDC_EDIT_LOG_SIZE               1101
#define IDC_CHECK_LOG_ENABLE2           1102
#define IDC_CHECK_SEPARATE_CS           1102
#define IDC_EDIT_ID                     1111
#define IDC_MASK_0                      1112
#define IDC_MASK_1                      1113
#define IDC_MASK_2                      1114
#define IDC_MASK_3                      1115
#define IDC_MASK_4                      1116
#define IDC_MASK_5                      1117
#define IDC_MASK_6                      1118
#define IDC_MASK_7                      1119
#define IDC_SELECT_BASE                 1121
#define IDC_SELECT_CUSTOM               1122
#define IDC_COMBO_VCC                   1124
#define IDC_BUTTON_CHECK                1125
#define IDC_EDIT_TASK                   1126
#define IDC_LABLE_ID                    1127
#define IDC_LABLE_VENDOR                1128
#define IDC_LABLE_ONFI                  1129
#define IDC_LABLE_CE0                   1130
#define IDC_LABLE_CE1                   1131
#define IDC_LABLE_CE2                   1132
#define IDC_LABLE_CE3                   1133
#define IDC_LABLE_BUS                   1134
#define IDC_LABEL_RECORDS               1135
#define IDC_BUTTON_RESET                1137
#define IDC_RECORD_SRC                  1138
#define IDC_RECORD_DST                  1139
#define IDC_FINISH_INFO                 1140
#define IDC_INFO_ID                     1141
#define IDC_EDIT_DIRECTORY              1143
#define ID_READER_CONNECT               32771
#define ID_READER_START                 32773
#define ID_READER_STOP                  32774
#define ID_READER_SETTINGS              32777
#define ID_NEW_NOTREADED                32778
#define ID_NEW_READEDONCE               32779
#define ID_NEW_VERIFYERROR              32780
#define ID_NEW_VERIFYOK                 32781
#define ID_NEW_CORRECTEDHIGH            32782
#define ID_NEW_CORRECTEDLOW             32783
#define ID_DATABASE_IMPORT              32785
#define ID_DATABASE_EDIT                32786
#define ID_DATABASE_MERGE               32791
#define ID_DATABASE_EXPORT              32805
#define ID_INDICATOR_READER             59143
#define IDS_CONNECT_BUSY                61210
#define IDS_GEOMETRY                    61211
#define IDS_WRONG_TASK_NAME             61213
#define IDS_WRONG_PURTNUMBER            61214
#define IDS_WRONG_VENDOR                61215
#define IDS_WRONG_VENDOR_INPUT          61216
#define IDS_WRONG_VENDOR_REMOVE         61217
#define IDS_PROMPT_REMOVE               61218
#define IDS_WRONG_READER                61219
#define IDS_READER_BUSY                 61220
#define IDS_READER_BAD                  61221
#define IDS_WRONG_TASK                  61222
#define IDS_TASK_EXISTS                 61223
#define IDS_CHECK_FLASH                 61224
#define IDS_READ_FLASH_ERROR            61225
#define IDS_ERROR_READ_FLASH            61225
#define IDS_ERROR_NO_FLASH              61226
#define IDS_READ_FILE_ERROR             61227
#define IDS_ERROR_READ_FILE             61227
#define IDS_WRONG_FILE                  61228
#define IDS_NO_FLASH                    61229
#define IDS_WRONG_TASK_FILE             61230
#define IDS_WRONG_TASK_VERSION          61231
#define IDS_WRONG_STEP_COUNT            61232
#define IDS_READ_ONCE                   61233
#define IDS_VERIFY                      61234
#define IDS_BIT_CORRECTION              61235
#define IDS_SUBTASK_START               61236
#define IDS_SUBTASK_COMPLETE            61237
#define IDS_SUBTASK_BREAK               61238
#define IDS_SUBTASK_ERROR               61239
#define IDS_WRITE_FILE_ERROR            61240
#define IDS_ERROR_WRITE_FILE            61240
#define IDS_TASK_NEW                    61241
#define IDS_TASK_LOAD                   61242
#define IDS_PROMT_IMPORT                61243
#define IDS_WRONG_WINDOWS               61244
#define IDS_WRONG_FILE_SYSTEM           61245
#define IDS_ERROR_LOG_FILE              61246
#define IDS_CHIP_NOT_PRESENT            61247
#define IDS_PROMT_MERGE                 61248
#define IDS_WRONG_PARAMETERS_PAGE       61249
#define IDS_SELECT_DIRECTORY            61250
#define IDS_THREAD_ERROR                61251
#define IDS_POWER_FAIL                  61252
#define IDS_POWER_HIGH                  61253
#define IDS_POWER_LOW                   61254
#define IDS_POWER_FAIL4                 61255
#define IDS_POWER_UNKNOWN               61255
#define IDS_ERROR_WRITE_FILE2           61256
#define IDS_ERROR_POWER                 61256

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
